# Basic
server:
  port: 8888
  servlet:
    context-path: /onlineExam

# Spring
spring:
  mvc:
    favicon:
      enabled: true
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: false
  profiles:
    active: druid

# MyBatis
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: cn.edu.hstc.pojo,cn.edu.hstc.vo,cn.edu.hstc.po
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath:mybatis-mapper/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:config/mybatis-config.xml

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# 日志配置
logging:
  level:
    cn.edu: debug
    org.springframework: warn